- crm-base-api/src/controllers/UsersController.ts
- crm-base-api/src/models/userdetails/IUserDetails.ts
- crm-base-api/src/models/userdetails/UserDetails.ts
- crm-base-api/src/models/users/IUsers.ts
- crm-base-api/src/models/users/Users.ts
- crm-base-api/src/models/users/payload/response/UserInfoResponse.ts
- crm-base-api/src/repositories/UsersRepository.ts
- crm-base-api/src/services/UsersService.ts
- crm-base-api/src/test/integration/users.controller.spec.ts
- crm-base-api/src/test/unit/services/users.service.spec.ts
- Implement the process of getting User info endpoint
- Define UserDetails with User
- Revise Controller and Service Tests according to UserDetails with User
- Add Controller and Service tests for getting User info endpoint
> PR : Get User Info Endpoint and Revise Controller and Service Tests

- .github/workflows/label_close_merge.yml
> Revise file

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
The pull request is connected with #44
> #PR 9 : Add Code of Product and Contributing Markdown file for Github Community Standards

- SECURITY.md
The pull request is related with #46
> PR # 10 : Add Security Markdown file for Github Community Standards

- CODEOWNERS
This pull request is related with #48
> PR #11 : Add CODEOWNERS

- PULL_REQUEST_TEMPLATE.md
The pull request is related with #54
> PR #14 : Add Pull Request Template markdown file

- README.md
We need to enhance the visibility of our project's build status by adding a status badge to the README.md file. This badge will provide at-a-glance information about the build status from our CI/CD pipeline (GitHub Actions) and help maintain transparency about the current state of the project.
Link to the issue this pull request addresses: #56 
- The code is formatted according to the …
> Add Application Badge Status in README.md

- README.md
PR 16 : Remove Merge Status Badge from Readme.md
Link to the issue this pull request addresses: #58 
- Necessary documentation has been added or existing documentation has been updated, specifically …
> PR 16 : Remove Merge Label Status Label from README.md

- .github/workflows/label_close_merge.yml
- Define an **action** named **Remove 'review' Label from PR** in `label_close_merge.yml` instead of **Remove 'development' Label from PR**
- Define an **action** named **Remove 'review' Label from Issue** in `label_close_merge.yml` instead of **Remove 'review' Label from Issue**
Link to the issue this pull request addresses: #64 
- The code is formatted according to the project's coding …
> Use Label Close for Review instead of Development

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #1): Add a new Jobs for Archiving test results and Sending test report email

- package.json
> PR #26 (Updated #3): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
- package.json
- yarn.lock
> PR #26 (Updated #4): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
- crm-base-api/yarn.lock
- package.json
> PR #26 (Updated #5): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #6): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #7): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #8): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #9): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #11): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #12): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #13): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #14): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #15): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #16): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #17): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #18): Add a new Jobs for Archiving test results and Sending test report email

- .github/workflows/label_close_merge.yml
> PR #26 (Updated #19): Add a new Jobs for Archiving test results and Sending test report email

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
Define 3 Issue template shown below.
- Bug Report
- Feature Request
- Custom Issue Template
Link to the issue this pull request addresses: #102  
- Necessary documentation has been added or existing …
> PR #27 :  Define Issue Template for Repo
